/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generators/generate-widget-kind-configs.ts
 * 
 * Widget Kind Default Configurations
 * Contains default configurations for each widget kind, including settings defaults
 * extracted from widget JSON schemas.
 */

import Foundation

/// Widget kind default configurations
class WidgetKindConfigs {
    /// All supported widget kinds
    static let widgetKinds = ["DailyWeatherWidget", "ForecastWeatherWidget", "HourlyWeatherWidget", "SimpleWeatherWidget", "SimpleWeatherWithClockWidget", "SimpleWeatherWithDateWidget"]
    
    /// Get default settings for a widget kind
    /// - Parameter widgetKind: The widget kind
    /// - Returns: Dictionary of default settings, or nil if no settings
    static func getDefaultSettings(widgetKind: String) -> [String: Any]? {
        switch widgetKind {
        case "DailyWeatherWidget":
            return [
                "showChips": true
            ]
        case "ForecastWeatherWidget":
            return [
                "showChips": true
            ]
        case "HourlyWeatherWidget":
            return nil
        case "SimpleWeatherWidget":
            return [
                "showChips": true
            ]
        case "SimpleWeatherWithClockWidget":
            return [
                "clockBold": false,
                "showHourly": false,
                "showChips": true
            ]
        case "SimpleWeatherWithDateWidget":
            return [
                "clockBold": false,
                "showHourly": false,
                "showChips": true
            ]
        default:
            return nil
        }
    }
    
    /// Create default config for a widget kind
    /// - Parameter widgetKind: The widget kind
    /// - Returns: Widget configuration with defaults from schema
    static func createDefaultKindConfig(widgetKind: String) -> WidgetConfig {
        return WidgetConfig(
            locationName: "current",
            latitude: 0.0,
            longitude: 0.0,
            model: nil,
            provider: nil,
            widgetKind: widgetKind,
            iconSet: nil,
            settings: getDefaultSettings(widgetKind)
        )
    }
}
