platform :ios, '13.0'
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            end
            config.build_settings['DEVELOPMENT_TEAM'] = '3UUB5NM43K'
            # CocoaPods only clears the identity for iOS SDKs: Catalyst pods would need a
            # "Mac Development" cert. Sign them ad-hoc, the embed phase re-signs with the app identity.
            config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
            config.build_settings['SWIFT_VERSION'] = '5.1'
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
            config.build_settings['OTHER_SWIFT_FLAGS'] = '-DSUPPRESS_WARNINGS'
        end
    end
end